version: '3.3'
services:
        ninjam:
                image: zeppelinux/ninjam-server:v0.084
                ports:
                        - "2049:2049"
                container_name: ninjam
                restart: always
                volumes:
                        - $NINJAM_PATH/cclicense.txt:/usr/local/ninjam/cclicense.txt
                        - $NINJAM_PATH/config.cfg:/usr/local/ninjam/config.cfg
